# embed_ptx.cmake
# Reads a PTX text file and writes a C header embedding it as a null-terminated
# string literal.
#
# Variables (passed via -D on the cmake -P command line):
#   PTX_FILE    — path to the input .ptx file
#   OUTPUT_FILE — path for the generated .h file
#
# The generated header defines:
#   static const char* kOptixProgramsPtx = "...";

cmake_minimum_required(VERSION 3.21)

if(NOT PTX_FILE)
    message(FATAL_ERROR "PTX_FILE is not set")
endif()
if(NOT OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is not set")
endif()

file(READ "${PTX_FILE}" _ptx)

# Escape for a C string literal: backslashes first, then double-quotes.
string(REPLACE "\\" "\\\\" _ptx "${_ptx}")
string(REPLACE "\"" "\\\"" _ptx "${_ptx}")
# Replace each newline with \n followed by a new line of string literal so the
# generated file stays readable and avoids extremely long lines.
string(REPLACE "\n" "\\n\"\n\"" _ptx "${_ptx}")

file(WRITE "${OUTPUT_FILE}"
    "// Auto-generated by cmake/embed_ptx.cmake — do not edit.\n"
    "#pragma once\n"
    "static const char* kOptixProgramsPtx =\n"
    "\"${_ptx}\";\n"
)
